### ISSUE TITLE
 Not able to find the Ip Address.

### ISSUE THREAD

**Issue by bugrevealingbme** [pradyotprksh/ip_address#1]
AsyncSnapshot<dynamic>(ConnectionState.done, null, Not able to find the Ip Address., #0      NetworkRequest.getIpAddressJson

**Comment by pradyotprksh** [comment]
Hey, can you share the code which you are using? Not able to replicate it.

**Comment by pradyotprksh** [comment]
Closing this for now, until further response.

**Comment by bugrevealingbme** [comment]
I fixed with this:

class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}


 main() async {
  HttpOverrides.global = MyHttpOverrides();
